name: npm build, test
on: 
  push:
    branches:
      - develop

jobs:
  build-and-test:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Print a Greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Yong
          LAST_NAME: Wang
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME

      - name: Checkout develop branch
        uses: actions/checkout@1

      - uses: actions/setup-node@v1
        with:
          node-version: lastest

      - run: npm install
      - run: npm test
      
      - name: Echo END
        run: echo 'CI ENDS -- :)'
