name: first-workflow
on: 
  push:
    branches:
      - master

jobs:
  build:
    # Job name is greeting
    name: FirstWorkflow
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Hello Octocat'
        id: hello

      - name: Echo the greeting time
        run: echo 'the time was ${{ steps.hello.outputs.time }}.'
